/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterCourseRouteImport } from './routes/register-course'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileFormRouteImport } from './routes/profile-form'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MainRouteImport } from './routes/main'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as InstructionRouteImport } from './routes/instruction'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultIndexRouteImport } from './routes/result/index'
import { Route as ResultIdRouteImport } from './routes/result/$id'

const RegisterCourseRoute = RegisterCourseRouteImport.update({
  id: '/register-course',
  path: '/register-course',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFormRoute = ProfileFormRouteImport.update({
  id: '/profile-form',
  path: '/profile-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructionRoute = InstructionRouteImport.update({
  id: '/instruction',
  path: '/instruction',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIndexRoute = ResultIndexRouteImport.update({
  id: '/result/',
  path: '/result/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultIdRoute = ResultIdRouteImport.update({
  id: '/result/$id',
  path: '/result/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/home': typeof HomeRoute
  '/instruction': typeof InstructionRoute
  '/logout': typeof LogoutRoute
  '/main': typeof MainRoute
  '/profile': typeof ProfileRoute
  '/profile-form': typeof ProfileFormRoute
  '/register': typeof RegisterRoute
  '/register-course': typeof RegisterCourseRoute
  '/result/$id': typeof ResultIdRoute
  '/result/': typeof ResultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/home': typeof HomeRoute
  '/instruction': typeof InstructionRoute
  '/logout': typeof LogoutRoute
  '/main': typeof MainRoute
  '/profile': typeof ProfileRoute
  '/profile-form': typeof ProfileFormRoute
  '/register': typeof RegisterRoute
  '/register-course': typeof RegisterCourseRoute
  '/result/$id': typeof ResultIdRoute
  '/result': typeof ResultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fees': typeof FeesRoute
  '/home': typeof HomeRoute
  '/instruction': typeof InstructionRoute
  '/logout': typeof LogoutRoute
  '/main': typeof MainRoute
  '/profile': typeof ProfileRoute
  '/profile-form': typeof ProfileFormRoute
  '/register': typeof RegisterRoute
  '/register-course': typeof RegisterCourseRoute
  '/result/$id': typeof ResultIdRoute
  '/result/': typeof ResultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fees'
    | '/home'
    | '/instruction'
    | '/logout'
    | '/main'
    | '/profile'
    | '/profile-form'
    | '/register'
    | '/register-course'
    | '/result/$id'
    | '/result/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fees'
    | '/home'
    | '/instruction'
    | '/logout'
    | '/main'
    | '/profile'
    | '/profile-form'
    | '/register'
    | '/register-course'
    | '/result/$id'
    | '/result'
  id:
    | '__root__'
    | '/'
    | '/fees'
    | '/home'
    | '/instruction'
    | '/logout'
    | '/main'
    | '/profile'
    | '/profile-form'
    | '/register'
    | '/register-course'
    | '/result/$id'
    | '/result/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FeesRoute: typeof FeesRoute
  HomeRoute: typeof HomeRoute
  InstructionRoute: typeof InstructionRoute
  LogoutRoute: typeof LogoutRoute
  MainRoute: typeof MainRoute
  ProfileRoute: typeof ProfileRoute
  ProfileFormRoute: typeof ProfileFormRoute
  RegisterRoute: typeof RegisterRoute
  RegisterCourseRoute: typeof RegisterCourseRoute
  ResultIdRoute: typeof ResultIdRoute
  ResultIndexRoute: typeof ResultIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-course': {
      id: '/register-course'
      path: '/register-course'
      fullPath: '/register-course'
      preLoaderRoute: typeof RegisterCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-form': {
      id: '/profile-form'
      path: '/profile-form'
      fullPath: '/profile-form'
      preLoaderRoute: typeof ProfileFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/main': {
      id: '/main'
      path: '/main'
      fullPath: '/main'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruction': {
      id: '/instruction'
      path: '/instruction'
      fullPath: '/instruction'
      preLoaderRoute: typeof InstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/': {
      id: '/result/'
      path: '/result'
      fullPath: '/result/'
      preLoaderRoute: typeof ResultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$id': {
      id: '/result/$id'
      path: '/result/$id'
      fullPath: '/result/$id'
      preLoaderRoute: typeof ResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FeesRoute: FeesRoute,
  HomeRoute: HomeRoute,
  InstructionRoute: InstructionRoute,
  LogoutRoute: LogoutRoute,
  MainRoute: MainRoute,
  ProfileRoute: ProfileRoute,
  ProfileFormRoute: ProfileFormRoute,
  RegisterRoute: RegisterRoute,
  RegisterCourseRoute: RegisterCourseRoute,
  ResultIdRoute: ResultIdRoute,
  ResultIndexRoute: ResultIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
